# Generated by Django 4.1 on 2022-12-07 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRatingAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('VERYPOSITIVE', 'Very Positive'), ('SOMEWHATPOSITIVE', 'Somewhat Positive'), ('NEUTRAL', 'Negative'), ('SOMEWHATNEGATIVE', 'Somewhat Negative'), ('VERYNEGATIVE', 'Very Negative')], help_text='Overall, how would you rate the quality of your customer service experience', max_length=50)),
                ('q2', models.CharField(choices=[('EXTREMELYWELL', 'Extremely Well'), ('VERYWELL', 'Very well'), ('SOMEWHATWELL', 'Somewhat Well'), ('NOTSOWELL', 'Not So Well'), ('NOTATALLWELL', 'Not at all well')], help_text='How well we understand and address your questions and concerns?', max_length=50)),
                ('q3', models.CharField(choices=[('MUCHSHORTERTHANEXPECTED', 'Much shorter than expected'), ('ABOUTWHATIEXPECT', 'About what I expected'), ('SHORTERTHANEXPECTED', 'Shorter than expected'), ('LONGERTHANIEXPECTED', 'Longer than I expected'), ('MUCHLONGERTHANIEXPECTED', 'Much longer than I expected')], help_text='How much time did it take us to address your questions and concerns?', max_length=50)),
                ('q4', models.IntegerField(help_text='How likely is it that you would recommend our company/product/services to a friend or colleagues? Rate us between 1 to 5, wherein 5 is the Highest and 1 is the Lowest: ')),
                ('q5', models.TextField(blank=True, help_text='Do you have any other comments, question or concerns', max_length=500, null=True)),
                ('q6', models.CharField(blank=True, help_text='Do you know the name of the person who assisted you', max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_employeeratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Satisfaction Ratings',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('signature', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Absences',
            },
        ),
    ]
