# Generated by Django 4.1 on 2022-12-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_absences_user_alter_attendance_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerratinganswers',
            name='q1_score',
            field=models.IntegerField(default=1, help_text='Index of question 1'),
        ),
        migrations.AddField(
            model_name='customerratinganswers',
            name='q2_score',
            field=models.IntegerField(default=1, help_text='Index of question 2'),
        ),
        migrations.AddField(
            model_name='customerratinganswers',
            name='q3_score',
            field=models.IntegerField(default=1, help_text='Index of question 3'),
        ),
    ]
