# Generated by Django 4.1 on 2022-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='signature',
            field=models.TextField(max_length=1000),
        ),
    ]
