# Generated by Django 4.1 on 2022-12-02 15:45

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_attendance_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='signature',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
