# Generated by Django 4.1 on 2022-12-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_attendance_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerratinganswers',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
