# Generated by Django 4.1 on 2022-12-03 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_customerratinganswers_q5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerratinganswers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
