# Generated by Django 4.1 on 2022-12-23 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_attendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
