# Generated by Django 4.1 on 2022-12-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_absences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerratinganswers',
            options={'verbose_name_plural': 'Customer Satisfaction Ratings'},
        ),
    ]
