# Generated by Django 4.1 on 2022-12-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_attendance_completed_attendance_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='minutes_late',
            field=models.IntegerField(default=0),
        ),
    ]
