# Generated by Django 4.1 on 2022-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_attendance_minutes_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='minutes_late',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
