# Generated by Django 4.1 on 2022-12-06 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_customerratinganswers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerratinganswers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
