# Generated by Django 4.1 on 2023-01-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_attendance_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerratinganswers',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
