# Generated by Django 4.1 on 2023-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_customerratinganswers_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='completionReport',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
