# Generated by Django 4.1 on 2023-01-29 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
