# Generated by Django 4.1 on 2023-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
