# Generated by Django 4.1 on 2022-12-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mi', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('SALESEXECUTIVE', 'Sales Executive'), ('TECHNICIAN', 'Tecnician')], default='SALESEXECUTIVE', max_length=20)),
                ('date_hired', models.DateTimeField()),
            ],
        ),
    ]
