# Generated by Django 4.1 on 2022-12-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='next_sunday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
