# Generated by Django 4.1 on 2022-12-07 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_period', models.CharField(max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_evaluation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evaluation',
            },
        ),
        migrations.CreateModel(
            name='EvaluationRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CORE', 'Core'), ('KPI', 'KPI')], default='CORE', max_length=20)),
                ('employee_type', models.CharField(choices=[('SALESEXECUTIVE', 'Sales Executive'), ('TECHNICIAN', 'Tecnician')], default='SALESEXECUTIVE', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rubrics',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_deal', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CORE', 'Core'), ('KPI', 'KPI')], default='CORE', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employee_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_evaluation', to='hr.employeeevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='BackJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_backjobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Backjobs',
            },
        ),
    ]
