# Generated by Django 4.1 on 2022-12-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backjobs',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
