# Generated by Django 4.1 on 2022-12-25 02:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_backjobs_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('has_rating', models.BooleanField(default=False)),
                ('has_backjob', models.BooleanField(default=False)),
                ('has_sales', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Employee Position',
            },
        ),
        migrations.CreateModel(
            name='RubricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('emplyee_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_template', to='hr.employeepositions')),
            ],
            options={
                'verbose_name_plural': 'Rubric Template',
            },
        ),
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('template_name', models.CharField(default='none', max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rubric_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='hr.rubrictemplate')),
            ],
            options={
                'verbose_name_plural': 'Rubric Criteria',
            },
        ),
    ]
