# Generated by Django 4.1 on 2022-12-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_evaluationrubric_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrubric',
            name='type',
            field=models.CharField(choices=[('CORE', 'Core'), ('KPI', 'KPI')], default='CORE', max_length=20),
        ),
    ]
