# Generated by Django 4.1 on 2022-12-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeepositions_rubrictemplate_rubriccriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRubricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeEvaluationDetail',
        ),
        migrations.AddField(
            model_name='evaluationrubrictemplate',
            name='employee_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rubric', to='hr.employeeevaluation'),
        ),
        migrations.AddField(
            model_name='evaluationrubriccriteria',
            name='employee_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='hr.evaluationrubrictemplate'),
        ),
    ]
