# Generated by Django 4.1 on 2022-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_employeeevaluationdetail_rubric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevaluationdetail',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
