# Generated by Django 4.1 on 2022-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employeeevaluationdetail_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevaluation',
            name='review_period',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
