# Generated by Django 4.1 on 2022-12-03 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employeeevaluation_review_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevaluation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
