# Generated by Django 4.1 on 2022-12-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employeeevaluation_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrubric',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
