# Generated by Django 4.1 on 2022-12-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_sales_backjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
