# Generated by Django 4.1 on 2022-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevaluationdetail',
            name='type',
            field=models.CharField(choices=[('CORE', 'Core'), ('KPI', 'KPI')], default='CORE', max_length=20),
        ),
    ]
