# Generated by Django 4.1 on 2022-12-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_employeeevaluationdetail_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backjobs',
            options={'verbose_name_plural': 'Backjobs'},
        ),
        migrations.AlterModelOptions(
            name='employeeevaluation',
            options={'verbose_name_plural': 'Evaluation'},
        ),
        migrations.AlterModelOptions(
            name='evaluationrubric',
            options={'verbose_name_plural': 'Rubrics'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
    ]
